# Generated by Django 3.1.6 on 2021-06-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
            ],
        ),
    ]
